import "../globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import SideNav from "../component/SideNav";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="bg-[#F3F3F7]">
        <SideNav>{children}</SideNav>
      </body>
    </html>
  );
}
