import "../globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import SideNav from "../component/SideNav";
import { Suspense } from "react";
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <SideNav>{children}</SideNav>
    </section>
  );
}
