import "../globals.css";
import type { Metadata } from "next";
import SideNav from "../component/SideNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <div className="bg-[#F3F3F7] h-full">
        <SideNav>{children}</SideNav>
      </div>
    </section>
  );
}
