import "./globals.css";
import type { Metadata } from "next";
import { NextUIProvider } from "@nextui-org/react";
import { Roboto } from "next/font/google";
import Toastify from "./component/Toasify";
import { Providers } from "./providers";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="bg-[#F3F3F7] md:h-screen h-full">
        <Providers>
          {children}
          <Toastify />
        </Providers>
      </body>
    </html>
  );
}
